name: traffic_router
description: Route to different app pages based on traffic
version: 0.1.0
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  appsflyer_sdk: ^6.8.2
  firebase_database: ^9.1.4
  firebase_core: ^1.22.0
  android_play_install_referrer: ^0.2.1
  device_info_plus: ^4.1.2
  shared_preferences: ^2.0.15
  devicelocale: 0.5.2
  sim_info:
    git:
      url: https://github.com/arefhosseini/flutter_sim_info
  package_info_plus: ^1.4.3+1
  http: ^0.13.5
  url_launcher: ^6.1.5
  battery_plus: ^2.1.4+1
  root_check: ^0.0.2+1
  advertising_id: ^2.3.0
  flutter_facebook_sdk:
    git:
      url: https://github.com/MrOlolo/flutter_facebook_sdk


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

# To add assets to your package, add an assets section, like this:
# assets:
#   - images/a_dot_burr.jpeg
#   - images/a_dot_ham.jpeg
#
# For details regarding assets in packages, see
# https://flutter.dev/assets-and-images/#from-packages
#
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/assets-and-images/#resolution-aware.

# To add custom fonts to your package, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts in packages, see
# https://flutter.dev/custom-fonts/#from-packages
